# --- !Ups

create table "vehicleregistration" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "regnumber" varchar not null,
  "vehiclemake" varchar not null,
  "v5cdocref" varchar
);
# --- !Downs

drop table "vehicleregistration" if exists;
